name: "os matrix python app CI workflow "

on:
  push:
    branches: [ dev ]



jobs:


# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-a-specific-python-version
  build-python-tox-os-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.7", "3.8", "3.9"]
        app: [app1]
        # app: [app1,app2]
    name: "Running tests with tox (os matrix)"
    # runs-on: ubuntu-latest     
    runs-on: ${{ matrix.os }}   
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Install Tox and any other packages"
        run: pip install tox
      - name: "Run Tox"
        # Run tox using the version of Python in `PATH`
        # run: tox -e py
        run: cd ${{ matrix.app }} && tox -e py

