name: "ubuntu matrix python app CI workflow "

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 

 
  


jobs:


# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-a-specific-python-version
  build-python-tox-ubuntu-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
        python: ["3.7", "3.8", "3.9"]
        app: [app1]
    name: "Running tests with tox (ubuntu matrix)"
    # runs-on: ubuntu-latest     
    runs-on: ${{ matrix.os }}   
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Install Tox and any other packages"
        run: pip install tox
      - name: "Run Tox"
        run: cd ${{ matrix.app }} && tox -e py


        